[platformio]
default_envs = blink, serial_hello, counter, fibonacci

[common]
platform = atmelavr
board = uno
framework = arduino

[env:blink]
extends = common
build_src_filter = +<blink.cpp>

[env:serial_hello]
extends = common
build_src_filter = +<serial_hello.cpp>

[env:counter]
extends = common
build_src_filter = +<counter.cpp>

[env:fibonacci]
extends = common
build_src_filter = +<fibonacci.cpp>
